# Generated by Django 6.0.4 on 2026-04-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_compresion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='original_url',
            new_name='url',
        ),
    ]
